### ISSUE TITLE
Error `ICMP` protocol without `code` and `type`

### ISSUE THREAD

**Issue by YairSlobodin1** [np-guard/vpc-network-config-synthesis#186]
running
`../bin/vpcgen synth sg -c check/config_object.json -s check/conn_spec.json -o check/out.csv`

where the spec file is 
```
{
    "externals": {
        "e1": "1.0.0.0",
        "e2": "1.0.0.1"
    },
    "required-connections": [
        {
            "src": {
                "name": "proxy",
                "type": "instance"
            },
            "dst": {
                "name": "e1",
                "type": "external"
            },
            "allowed-protocols": [
                {
                    "protocol": "ICMP"
                }
            ]
        }
    ]
}
```

raises the following error:
```
2024/08/13 09:05:40 The following endpoints do not have required connections; the generated SGs will block all traffic:  test-vpc/appdata-endpoint-gateway, test-vpc/be, test-vpc/fe, test-vpc/opa, test-vpc/policydb-endpoint-gateway
2024/08/13 09:05:40 Impossible protocol {{<nil>} <nil>}
panic: Impossible protocol {{<nil>} <nil>}

goroutine 1 [running]:
log.Panicf({0x7d2051?, 0xc0006327e0?}, {0xc0004d9910?, 0x6c216d?, 0xc0004d9920?})
        C:/Users/YairSlobodin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/log/log.go:439 +0x65
github.com/np-guard/vpc-network-config-synthesis/pkg/io/csvio.printProtocolParams({0x8a77c0?, 0xc0006146a0?}, 0x18?)
        C:/Users/YairSlobodin/vpc-network-config-synthesis/pkg/io/csvio/sg.go:117 +0x110
github.com/np-guard/vpc-network-config-synthesis/pkg/io/csvio.makeSGRow(0xc000619900, {0xc0002b3750, 0xe})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/pkg/io/csvio/sg.go:49 +0x105
github.com/np-guard/vpc-network-config-synthesis/pkg/io/csvio.makeSGTable(0x737700?, {0xc0002b3750, 0xe})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/pkg/io/csvio/sg.go:58 +0x8f
github.com/np-guard/vpc-network-config-synthesis/pkg/io/csvio.(*Writer).WriteSG(0xc000298790, 0xc000298780, {0x0, 0x0})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/pkg/io/csvio/sg.go:23 +0x237
github.com/np-guard/vpc-network-config-synthesis/pkg/ir.(*SGCollection).Write(0xc00036e7e0?, {0x8a8f50?, 0xc000298790?}, {0x0?, 0x262025?})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/pkg/ir/sg.go:102 +0x2f
github.com/np-guard/vpc-network-config-synthesis/cmd/subcmds.writeCollection(0xc00036e7e0, {0x8a7760, 0xc000298780}, {0x0, 0x0})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/cmd/subcmds/output.go:74 +0x6e
github.com/np-guard/vpc-network-config-synthesis/cmd/subcmds.writeOutput(0xc00036e7e0, {0x8a7760, 0xc000298780}, 0xc000632798)
        C:/Users/YairSlobodin/vpc-network-config-synthesis/cmd/subcmds/output.go:45 +0x176
github.com/np-guard/vpc-network-config-synthesis/cmd/subcmds.synthesis(0xc00029fbb0?, 0xc00036e7e0, 0x818a20, 0x0)
        C:/Users/YairSlobodin/vpc-network-config-synthesis/cmd/subcmds/synth.go:39 +0x75
github.com/np-guard/vpc-network-config-synthesis/cmd/subcmds.NewSynthCommand.NewSynthSGCommand.func1(0xc0000bce00?, {0xc000192a20?, 0x4?, 0x7bcf28?})
        C:/Users/YairSlobodin/vpc-network-config-synthesis/cmd/subcmds/synthSG.go:22 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0001b0608, {0xc0001929c0, 0x6, 0x6})
        C:/Users/YairSlobodin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001dfb08)
        C:/Users/YairSlobodin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc000080000?)
        C:/Users/YairSlobodin/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
        C:/Users/YairSlobodin/vpc-network-config-synthesis/cmd/vpcgen/main.go:15 +0x18
```

note: there is no error when the output format is `tf` or `json`.

**Comment by YairSlobodin1** [comment]
Non problem
